### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aojea**

### CODE REVIEW

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
:shipit: 

/hold
Pro-tip: mark test PRs [WIP] in the title so they don't merge by drive-by LGTM :+)

**Comment by aojea** [comment]
oh, I just want to test the jobs

**Comment by BenTheElder** [comment]
yes, putting [WIP] in the title will ensure your test PR can't merge on accident.

you can also use an empty commit if you want to get fancy

**Comment by aojea** [comment]
@BenTheElder any clue before I start to add `ls` to the job XD?

```
wrapper.sh] [TEST] Running Test Command: `bash -c curl -sSL https://kind.sigs.k8s.io/dl/latest/linux-amd64.tgz | tar xvfz - -C "${PATH%%:*}/" && cd ./../../k8s.io/kubernetes && ./../../sigs.k8s.io/cloud-provider-kind/hack/ci/e2e.sh` ...
kind
e2e-k8s.sh
bash: line 1: ./../../sigs.k8s.io/cloud-provider-kind/hack/ci/e2e.sh: No such file or directory
```

**Pull request closed without merging**
