### PR TITLE
Only enable IPv6 on loadbalancer container when the service is ipv6

### PR DESCRIPTION
**Pull request by aojea**
Fixes: https://github.com/kubernetes-sigs/cloud-provider-kind/issues/111

### CODE REVIEW

**Comment by aojea** [comment]
> Kubernetes e2e suite: [It] [sig-network] LoadBalancers ExternalTrafficPolicy: Local [Feature:LoadBalancer] [Slow] should handle updates to ExternalTrafficPolicy field expand_less	

the test failure is a known issue, unrelated to this PR

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve

**Comment by BenTheElder** [comment]
hmm @aojea probably some more of these presubmits should be marked required?

**Comment by aojea** [comment]
> hmm @aojea probably some more of these presubmits should be marked required?

Indeed

**Comment by serbaut** [comment]
I think this issue has to be handled [here ](https://github.com/kubernetes-sigs/cloud-provider-kind/blob/main/pkg/gateway/envoy.go#L192 )as well. envoy fails to start on a host with ipv6 disabled.

**Pull request merged**
